### ISSUE TITLE
Huge Bug/ Problem

### ISSUE THREAD

**Issue by koolx** [sblask/webextension-simple-form-fill#10]
The autocomplete feature conflicts with Google's search. When I type a word in google search thats similar to the ones in the autocomplete's list, the items come up instead of the drop down words in google. How can I disable the app for search engines like google?

**Comment by sblask** [comment]
You can't. Your options are:

 - disable autocomplete altogether
 - increase minimum number of characters typed (see options) so it's less likely to get a match.
 - type faster ;-)
 - don't use the search field on Google's page (This is what I do and why it's not a problem for me. I only ever use the location bar of my browser for my initial search and if I need to refine, my query is long enough so there is no match. )

**Comment by koolx** [comment]
Hi Sebastian,

Thanks for replying. Theres got to be a way to disable the app when in google. I'm 100% sure you could add code to disable your app when google search pops up. Its not difficult to do.

Maybe I can ask someone in the FF forums to add code to your app to make this happen. What do you think?

**Comment by sblask** [comment]
It is not difficult, but my experience from other extensions tells me that this kind of request will just keep coming. Even if other people create pull requests, it costs my time. The main problem being that actually releasing the code can not be automated...

**Comment by koolx** [comment]
Sebastian,

I understand your position. But you got a winning app here. Its unique cuz theres no other app like it. All you need is just add a simple feature to disable it in certain sites like google, thats all. Its no big deal. Doing so will boost the value of your app. Thats reward in and of itself. I know CSS. Maybe I can use my skills to help you with this. 

Also the drop down menu in autocomplete is transparent. Hope you can add black background color to it. 

Let me know brother!!

**Comment by koolx** [comment]
Sabaastian,

Was wondering if you got around to fixing the issue. Would appreciate it. Thanks man

**Comment by sblask** [comment]
I have no plans on adding exceptions in the near future.

I fixed a transparency issue a few days ago. If you still have it with the current version, I'll need the page where it happens. The autocomplete is supposed to use the same style as is used for the input field unless it's transparent, then it defaults to black.

**Comment by koolx** [comment]
Hi Sebastian,

For the 1st issue, here's the page where the transparency persists:
https://ladyfreethinker.org/sign-justice-puppy-found-side-road-legs-ripped-off/#comment-722304

The fields (name, email, etc) to the right under, "SIGN THIS PETITION" show transparency.


2nd issue is when I enter a letter, it doesnt match just the 1st letter of the words I've listed. It matches any listed word with that letter in it. It should ONLY match the words starting with that 1st letter entered.

Hope you fix this soon. Thanks Sebastian.

**Comment by sblask** [comment]
First problem is fixed and I added an option for the second. Both in version 2.1.1 Submitted for Chrome and Firefox, but might take a bit to pop up.

**Comment by koolx** [comment]
Thank you Sebastian!

One last modification that can seal the deal that we discussed... please add an option to disable the addon in certain sites. This can help tremendously. Thanks man!
