### ISSUE TITLE
Form fill doesn't work inside iFrames

### ISSUE THREAD

**Issue by bryancasler** [sblask/webextension-simple-form-fill#108]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [x] Chrome

### What is your operating system?

- [ ] Linux
- [x] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Hello! We helped a non-profit client theme their Donation / Petition pages on top of a 3rd part service (Engaging Networks) that handles the heavy lifting. Recently one of our clients had a supporter reach out to let them know that an assistive plugin they use "Simple Form Fill" was not working for them on their forms. This was then forwarded to us and we looked into it.

First, thank you for creating such an incredible plugin and making it so easy to find you and provide feedback. Second, the issue turns out to only happen when the page is served via an iFrame. Below is an example that reproduces the problem. Just click "next" and then you will have a few form fields you can fill out.

We don't have any experience with plugin development but would be happy to provide any more details (if this is even something that is a possibility to fix).

Direct Page (works)
https://secure.everyaction.com/b1_ZpEtm4kSUe0BnLyQkug2

Same Page in iFrame (does not work)
https://codepen.io/4SiteStudios/pen/yLPLMyE

**Comment by sblask** [comment]
Hm, works for me on your codepen example. Maybe a conflict with some other extension?

**Comment by bryancasler** [comment]
Thank you. I tried it with a clean Chrome profile and only this extension. It did indeed work, I will report back.
