### ISSUE TITLE
Fill with multi lines of text

### ISSUE THREAD

**Issue by Narga** [sblask/webextension-simple-form-fill#13]
I have a paragraph with multi lines of text. How can I insert them in one click without choose then enter again, again and again.

**Comment by sblask** [comment]
You can't...

**Comment by tonglil** [comment]
Perhaps like the comment string, you can use the `\n` string and then change the character to a new line when filling out the form?

**Comment by sblask** [comment]
If someone wants to implement it, I am all for PRs, but I am not interested.
