### ISSUE TITLE
Unable to Upload Files to Specific Site 

### ISSUE THREAD

**Issue by geedogz** [sblask/webextension-simple-form-fill#132]
### New Issue Checklist (tick off like this: `[x]`)
- [ ] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?
- [ ] Firefox

### What is your operating system?
- [ ] Windows

### Description (please include examples/screenshots where applicable)
When I visit 'https://nyulangone-openhire.silkroad.com/epostings/' to try to upload my resume to the site, I'm unable to. Its only when this addon is disabled that uploading files to the site works.  Please fix big time.

**Comment by sblask** [comment]
I don't think there is anything I can do about it. It seems to me like the webpages do something weird. Your options are to disable autocomplete in Simple Form Fill or doing your upload in an incognito window assuming you have Simple Form Fill not enabled for incognito windows.
