### ISSUE TITLE
Version 2.1.1 stop working at FireFox 48

### ISSUE THREAD

**Issue by Iggnus** [sblask/webextension-simple-form-fill#16]
Hi Sebastian,
Can you please check the final comma?
https://github.com/sblask/webextension-simple-form-fill/blob/d96bcb1d97d293621c4d391e92b3d8299122895e/content-scripts/autocomplete.js#L21

**Comment by sblask** [comment]
Why are you using such an old version of Firefox? It's not even supported by Mozilla... You can always try an older version: https://addons.mozilla.org/en-US/firefox/addon/simple-form-fill/versions/ but I am not really into supporting older versions of Firefox or the extension...

**Comment by Iggnus** [comment]
Because of my intolerance to decreasing of adjustability/functionality
Also I need some XUL plugins. Probably I will be able to use higher versions of Cyberfox..
Who cares about Mozilla support? - They decide to turn something useful into another one chrome-like and castrated junk! (yes, I hate chrome, because of it my beloved Opera was murdered!)
Did they fix issue #12?

Without final comma at line 21  v2.1.1 works perfectly

**Comment by sblask** [comment]
This, I can understand. Still, why not 52ESR or even 56? Then you'd get the best of both worlds. I think webextensions are great, I just think there is no reason to remove XUL extensions. We'll see whether people see any reason to stay if it's just the same as Chrome. If you also liked Opera, did you check out Vivaldi? I think once it's got sync it will be good enough...

**Comment by Iggnus** [comment]
That's because FF46 was enough for me and 18 installed extensions just a few days ago.
With FF48 some of extension(unsigned) became blocked, so I moved to Cyberfox 48
52? - m.b. Did not check yet. And if they did not cutout something useful to me...
Vivaldi is not a good choice if you like to open 20-40 tabs %)  It looks less customizable..
Waiting for Otter Browser. I hope it becomes useful someday
