### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by ScottTu** [sblask/webextension-simple-form-fill#18]
couldnt find a better place to put this suggestion... only thing I'd like to have this is missing is for it to generate a random password and to repeat the last created password.

**Comment by sblask** [comment]
I think there are better extensions for that that also store passwords. I use LastPass for example. And looking at the choices you have there, I would have to write quite a bit of code to make it happen. But I want to keep it simple...

**Comment by ScottTu** [comment]
I dont want it to store passwords, just generate random passwords for when you're signing into a new sight. for example a 10 digit word with random letters and numbers in it. then have it be able to repeat the last one it generated because they always ask you to repeat your password to make sure you typed it right.  I use keepass myself.

**Comment by sblask** [comment]
I understood you. I am sure you don't *have* to store the password. So keepass does not have a generator? Or does it force you to store the password?

**Comment by ScottTu** [comment]
it does have a generator, just easier to have your form filler generate one.

**Comment by sblask** [comment]
This would do exactly what you want? https://addons.mozilla.org/en-GB/firefox/addon/secure-password-generator/?src=search

**Comment by ScottTu** [comment]
looks like it. thanks
