### ISSUE TITLE
Context menu disabled

### ISSUE THREAD

**Issue by bdcomp** [sblask/webextension-simple-form-fill#22]
The commit of #20 disabled the context menu, even the new option "Context Menu" is checked.

The only way to enable it is to uncheck and check it again.
This workaround works till closing the browser.

Simple Form Fill 2.1.5
Firefox 56 and 57
Kubuntu 17.10 64bit

**Comment by sblask** [comment]
Interesting, works fine in Chrome, I'll have a look...

**Comment by sblask** [comment]
Only worked in Chrome because of background apps, so it didn't actually close when I tried it.

**Comment by bdcomp** [comment]
Thanks a lot for your prompt fix!
It's appreciated.
