### ISSUE TITLE
left this on chrome...SFF is a great piece of work.

### ISSUE THREAD

**Issue by dooker123** [sblask/webextension-simple-form-fill#24]
### New Issue Checklist (tick off like this: `[x]`)

- [ ] I checked existing issues (open and closed) for possible duplicates
- [ x] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [ ] Firefox
- [x ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [ ] Windows

### Description (please include examples/screenshots where applicable)
left on chrome ratings ...i'd give this a 5 and pay good money if there were couple of things worked out. it should be attempted to make the program work on non-html pages in chrome. also the use tab or enter switch seems broke a bit, as in it won't go from enter to select, not to anything. Otherwise its a work of art. just the right amount of granularity. a simple text file looking entry page for terms. It would be nice to know any limits, such as word char count, if any, etc. WONDERFUL!

is any of that sensible?  thanks

**Comment by sblask** [comment]
Not sure what non-html pages there are where this would make sense?
Tab to select means that the next entry in the list gets selected and the cursor moves to the next field.
No limits that I know of...
