### ISSUE TITLE
Feature request: keyword search.

### ISSUE THREAD

**Issue by Dra9o** [sblask/webextension-simple-form-fill#41]
It would be nice if the extension would skip part of the line being inserted into the form. For example, if instead of 'main // bar // foo', 'foo' was inserted. This will actually enable search. In the context menu, it is desirable to display these items as submenus.

**Comment by sblask** [comment]
How would that be different from comments? If you set you comment string to `// ` you can write `foo // some descriptive key word`. I don't really want to add yet another way of doing that. I can see that having context menu submenus might be beneficial for some, but having a flat format is a feature in itself, It's the `simple` in Simple Form Fill. I also see the autocomplete and filtering in there as the main feature.
