### ISSUE TITLE
autocomplete doen't work on input type ="text"

### ISSUE THREAD

**Issue by keshav21786** [sblask/webextension-simple-form-fill#52]
The addon works very fine in search field, however i want autocomplete feature to run on field with input type= "text". Currently, the addon incremental search function doesn't run on text field. Please help.. Thanks!!!

 I checked existing issues (open and closed) for possible duplicates
 I am using Firefox.
 Operating system-- Windows 10

- [ x
![1](https://user-images.githubusercontent.com/73459429/97139074-b03ceb80-177f-11eb-8cbd-76447283e6f1.JPG)
![2](https://user-images.githubusercontent.com/73459429/97139075-b16e1880-177f-11eb-9309-eba73705cc37.JPG)

] Windows

**Comment by sblask** [comment]
This is an intentional limitation. Simple Form Fill is single line based whereas textareas are multiline which makes it too complicated to get right. You can always use the context menu to fill a text area.
