### ISSUE TITLE
Slow loading in a long word list

### ISSUE THREAD

**Issue by vladnero** [sblask/webextension-simple-form-fill#8]
Dropdown list loads slowly when word/phrase list has 1500+ items.

Suggestion: give user an opportunity to set a number of symbols (in settings) when symbol searching should start. For example, if "4" is set - it means that dropdown list forms only when typed string length >= 4. It should reduce a number of items in dropdown list.
There is another way (more optimised) - start to form a dropdown list only when Alt (or other non symbol button) was pressed.

**Comment by sblask** [comment]
I had wanted to implement the configurable minimum for a long time, I just kept on forgetting. Now it's done. Once you got updated to version 2.1.0 you'll have it.
