### ISSUE TITLE
Extension should only appear in text fields

### ISSUE THREAD

**Issue by Reggie521** [sblask/webextension-simple-form-fill#82]
### New Issue Checklist (tick off like this: `[x]`)

- [x] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [x] Windows

### Description (please include examples/screenshots where applicable)

Currently, Simple Form Fill appears in the standard right click context menu, with no options available since there is nothing to fill in. It should only appear in the context menu for text fields.

<img width="243" alt="fxcontext" src="https://user-images.githubusercontent.com/35973596/121022094-08a18600-c770-11eb-8998-11a805001765.png">

**Comment by sblask** [comment]
I don't agree.
