### ISSUE TITLE
Extension doesn't work until webpage is fully loaded

### ISSUE THREAD

**Issue by vladnero** [sblask/webextension-simple-form-fill#9]
There are many service scripts (ads, sync, track, stats, social networks etc.) that are loaded before this extension. So it can take a minute or more to load webpage. And if webpage isn't fully loaded (spinning circle in browser tab) this extension won't work,
Example: http://fieldbitcoins.com (window with SolveMedia captcha)

**Comment by sblask** [comment]
You probably want to use this: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
Nothing much I can do, if the page hasn't loaded yet, I can't inject the autocomplete.
