### ISSUE TITLE
Provide autofill based on id/class

### ISSUE THREAD

**Issue by MrCodeB2** [sblask/webextension-simple-form-fill#92]
### New Issue Checklist (tick off like this: `[x]`)

- [x ] I checked existing issues (open and closed) for possible duplicates
- [ ] I can reproduce the problem on the latest stable version (not nightly!)

### What is your browser?

- [x ] Firefox
- [ ] Chrome

### What is your operating system?

- [ ] Linux
- [ ] Mac
- [ x] Windows

### Description (please include examples/screenshots where applicable)
It would be great if i could definde some id/class_names to automatically fill the field with a specific value.

**Comment by sblask** [comment]
I am pretty sure there must be other extensions that can to that. This is SIMPLE Form Fill.
